#!/bin/bash
set -e

# elm-live/bin/elm-live.js src/Main.elm --pushstate --path-to-elm=node_modules/.bin/elm --no-hot-reloading --ide=atom --dir=docs --start-page=index.html --port=8001 -- --output=docs/elm-with-debugger.js --debug
# node_modules/.bin/elm-go src/Main.elm --pushstate --path-to-elm=node_modules/.bin/elm --dir=docs --start-page=index.html --port=8001 -- --output=docs/elm.js --debug
npx elm-watch@2.0.0-beta.3 hot main | cat

