#!/bin/bash
set -e
node_modules/.bin/elm-go src/Main2.elm --start-page=index2.html --pushstate --path-to-elm=node_modules/.bin/elm --dir=docs --start-page=index.html --port=8001 -- --output=docs/elm2.js --debug